// <auto-generated />
using MewMart.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MewMart.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204103149_addProductsToDB")]
    partial class addProductsToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MewMart.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Kattbollar"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Kattskålar"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Tygleksaker"
                        });
                });

            modelBuilder.Entity("MewMart.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrize")
                        .HasColumnType("float");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prize")
                        .HasColumnType("float");

                    b.Property<double>("Prize2")
                        .HasColumnType("float");

                    b.Property<double>("Prize5")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Grön kattboll",
                            ISBN = "AB212",
                            ListPrize = 25.0,
                            Manufacturer = "Made in China",
                            Prize = 23.0,
                            Prize2 = 21.0,
                            Prize5 = 18.0,
                            Title = "Grön kattboll"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Röd kattboll",
                            ISBN = "AB213",
                            ListPrize = 25.0,
                            Manufacturer = "Made in China",
                            Prize = 23.0,
                            Prize2 = 21.0,
                            Prize5 = 18.0,
                            Title = "Röd kattboll"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Grön kattskål",
                            ISBN = "AC212",
                            ListPrize = 25.0,
                            Manufacturer = "Made in China",
                            Prize = 23.0,
                            Prize2 = 21.0,
                            Prize5 = 18.0,
                            Title = "Grön kattskål"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Röd kattskål",
                            ISBN = "AC213",
                            ListPrize = 25.0,
                            Manufacturer = "Made in China",
                            Prize = 23.0,
                            Prize2 = 21.0,
                            Prize5 = 18.0,
                            Title = "Röd kattskål"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Röd Tygleksak",
                            ISBN = "AD215",
                            ListPrize = 25.0,
                            Manufacturer = "Made in China",
                            Prize = 23.0,
                            Prize2 = 21.0,
                            Prize5 = 18.0,
                            Title = "Röd Tygleksak"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Grön Tygleksakl",
                            ISBN = "AD218",
                            ListPrize = 25.0,
                            Manufacturer = "Made in China",
                            Prize = 23.0,
                            Prize2 = 21.0,
                            Prize5 = 18.0,
                            Title = "Grön Tygleksak"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
